// ACTION TYPES

export default {
  // ARTICLES
  FETCH_ARTICLES_START: 'FETCH_ARTICLES_START',
  FETCH_ARTICLES_ERROR: 'FETCH_ARTICLES_ERROR',
  FETCH_ARTICLES_COMPL: 'FETCH_ARTICLES_COMPL',

  // SENTIMENT
  FETCH_SENTIMENTS_START: 'FETCH_SENTIMENT_START',
  FETCH_SENTIMENTS_ERROR: 'FETCH_SENTIMENT_ERROR',
  FETCH_SENTIMENTS_COMPL: 'FETCH_SENTIMENT_COMPL'
};
